### Retrieve all notes
GET http://localhost:5000/notes


### Add a new note
POST http://localhost:5000/notes 
Content-Type: application/json

{
  "title": "task6", 
  "content": "solve task6"
}


### Delete a specific note using its ID
DELETE http://localhost:5000/notes/662f73fe7c1de82e65e498ff  


### Update a specific note using its ID
PUT http://localhost:5000/notes/66465aebd97733070ce1e135
Content-Type: application/json

{
  "title": "task44", 
  "content": "solve task44",
  "creationDate": "2024-05-04T00:00:00.000Z"
}
